import { escapeHtml, type EmailLocale } from './layout'

/**
 * Plantilla maestra de los emails propios de Portal INMO: la que llevan todos
 * los que la plataforma envía en su nombre (alta y estado de empresas, cuenta
 * de usuario, avisos del sistema y notificaciones al equipo de cada
 * inmobiliaria). Reproduce la referencia visual aprobada; ver docs/email.md.
 *
 * Una sola maqueta: cada email aporta sólo su CONTENIDO (antetítulo, título,
 * saludo, texto, datos y botón). La presentación —colores, medidas,
 * tipografía, bloque de contacto y pie— vive aquí, en `PORTAL_INMO_EMAIL`,
 * así que cambiarla cambia todos los emails a la vez.
 *
 * Maquetación de email, no de página web: tablas, estilos en línea y una
 * única regla `@media` para el móvil (los clientes que la ignoran ven la
 * versión de escritorio, que también cabe). Sin imágenes, sin scripts ni
 * seguimiento.
 */

export const PORTAL_INMO_EMAIL = {
  brand: { name: 'Portal', accent: 'INMO', tagline: ['TU ESPACIO', 'INMOBILIARIO'], footer: 'PORTAL INMO · GESTIÓN INMOBILIARIA' },
  width: 600,
  padding: 40,
  radius: 16,
  font: "Arial, 'Helvetica Neue', Helvetica, sans-serif",
  color: {
    background: '#EDF0EB',
    header: '#172C22',
    wordmark: '#FFFFFF',
    wordmarkAccent: '#EE856E',
    tagline: '#B8CBBB',
    lineAccent: '#E4765F',
    lineTrack: '#365043',
    surface: '#FFFFFF',
    eyebrow: '#BA513C',
    heading: '#172C22',
    text: '#536057',
    button: '#CC553F',
    buttonText: '#FFFFFF',
    divider: '#E4E9E1',
    signature: '#74806F',
    contactBackground: '#E4EBDF',
    contactHeading: '#263E2C',
    contactText: '#5D6E58',
    footer: '#7A8576',
  },
} as const

export interface MasterEmailContent {
  /** Texto pequeño en mayúsculas sobre el título («CONECTADOS CON TU ACTIVIDAD»). */
  eyebrow: string
  /** Título; `\n` marca un salto de línea fijo («Te damos la bienvenida a\nPortal INMO»). */
  title: string
  /** Nombre para «Hola, {nombre}:». Sin nombre, «Hola:» — nunca «undefined» ni un hueco. */
  greetingName?: string | null
  /** Párrafos de texto plano (se escapan); `**así**` resalta en negrita oscura. */
  paragraphs: string[]
  /** Datos del aviso («Empresa: …»), en el mismo cuerpo de texto. */
  details?: Array<[string, string | null | undefined]>
  cta?: { label: string; url: string } | null
  /** Texto tras el botón (p. ej. «Si no has solicitado…»). */
  footnote?: string | null
}

export interface MasterEmailContext {
  locale: EmailLocale
  /** Asunto: también va en <title>. */
  subject: string
  /** Correo del bloque «¿Hablamos?» (el de contacto de la plataforma). */
  contactEmail: string
}

const T = PORTAL_INMO_EMAIL
const attr = (s: string) => escapeHtml(s).replace(/"/g, '&quot;')
/** Texto plano → HTML: escapado, saltos de línea y `**negrita**`. */
function richText(s: string): string {
  return escapeHtml(s)
    .replace(/\*\*(.+?)\*\*/g, `<strong style="color:${T.color.heading};font-weight:700;">$1</strong>`)
    .replace(/\r?\n/g, '<br>')
}

const COPY: Record<EmailLocale, { hello: (name: string | null) => string; signature: [string, string]; contactTitle: string; contactText: string; generated: string }> = {
  es: {
    hello: (name) => (name ? `Hola, ${name}:` : 'Hola:'),
    signature: ['Seguimos a tu lado.', 'El equipo de Portal INMO'],
    contactTitle: '¿Hablamos?',
    contactText: 'Nuestro equipo está aquí para ayudarte.',
    generated: 'Este correo se ha generado desde la plataforma.',
  },
  en: {
    hello: (name) => (name ? `Hello, ${name}:` : 'Hello:'),
    signature: ['We are here for you.', 'The Portal INMO team'],
    contactTitle: 'Shall we talk?',
    contactText: 'Our team is here to help.',
    generated: 'This email was generated by the platform.',
  },
}

/** Nombre utilizable en el saludo, o null (vacío, «undefined», «null»…). */
export function greetingNameOf(name: unknown): string | null {
  const s = typeof name === 'string' ? name.trim() : ''
  if (!s || /^(undefined|null|\{\{.*\}\})$/i.test(s)) return null
  return s
}

export function renderMasterEmail(content: MasterEmailContent, ctx: MasterEmailContext): string {
  const c = T.color
  const copy = COPY[ctx.locale] || COPY.es
  const pad = T.padding
  const text = `margin:0;font-family:${T.font};font-size:16px;line-height:27px;color:${c.text};`
  const title = content.title
    .split('\n')
    .map((l) => escapeHtml(l))
    .join('<br>')
  const paragraphs = content.paragraphs.filter((p) => p && p.trim()).map((p) => `<p class="pi-text" style="${text}padding:0 0 20px;">${richText(p)}</p>`)
  const details = (content.details || []).filter(([, v]) => v != null && String(v).trim() !== '')
  const detailsHtml = details.length
    ? `<p class="pi-text" style="${text}padding:0 0 20px;">${details.map(([k, v]) => `<strong style="color:${c.heading};font-weight:700;">${escapeHtml(k)}:</strong> ${escapeHtml(String(v))}`).join('<br>')}</p>`
    : ''
  const cta = content.cta && content.cta.url
    ? `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:10px 0 0;"><tr>
<td align="center" bgcolor="${c.button}" style="border-radius:8px;background:${c.button};">
<a href="${attr(content.cta.url)}" target="_blank" style="display:inline-block;padding:16px 28px;font-family:${T.font};font-size:16px;line-height:21px;font-weight:700;color:${c.buttonText};text-decoration:none;border-radius:8px;">${escapeHtml(content.cta.label)}</a>
</td></tr></table>`
    : ''
  const footnote = content.footnote ? `<p class="pi-text" style="${text}padding:22px 0 0;">${richText(content.footnote)}</p>` : ''
  const preheader = escapeHtml(content.paragraphs.find((p) => p && p.trim()) || content.title.replace(/\n/g, ' ')).slice(0, 160)

  return `<!doctype html>
<html lang="${ctx.locale}" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>${escapeHtml(ctx.subject)}</title>
<style>
@media only screen and (max-width:620px){
  .pi-outer{padding:16px 10px 28px !important}
  .pi-pad{padding-left:24px !important;padding-right:24px !important}
  .pi-title{font-size:30px !important;line-height:34px !important}
}
</style>
</head>
<body style="margin:0;padding:0;background:${c.background};-webkit-text-size-adjust:100%;">
<div class="pi-preheader" style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${preheader}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${c.background}" style="background:${c.background};">
<tr><td class="pi-outer" align="center" style="padding:40px 16px 40px;">
<table role="presentation" width="${T.width}" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:${T.width}px;border-collapse:separate;">
<tr><td bgcolor="${c.header}" class="pi-pad" style="background:${c.header};border-radius:${T.radius}px ${T.radius}px 0 0;padding:32px ${pad}px 26px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
<td valign="middle" style="font-family:${T.font};font-size:30px;line-height:34px;font-weight:700;letter-spacing:-0.5px;color:${c.wordmark};">${T.brand.name} <span style="color:${c.wordmarkAccent};">${T.brand.accent}</span></td>
<td class="pi-tagline" valign="middle" align="right" style="font-family:${T.font};font-size:10.5px;line-height:12px;letter-spacing:1.7px;color:${c.tagline};text-align:right;">${T.brand.tagline.join('<br>')}</td>
</tr></table>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-top:32px;"><tr>
<td width="70" height="3" bgcolor="${c.lineAccent}" style="width:70px;height:3px;background:${c.lineAccent};font-size:0;line-height:0;">&nbsp;</td>
<td height="3" bgcolor="${c.lineTrack}" style="height:3px;background:${c.lineTrack};font-size:0;line-height:0;">&nbsp;</td>
</tr></table>
</td></tr>
<tr><td bgcolor="${c.surface}" class="pi-pad" style="background:${c.surface};padding:41px ${pad}px 40px;">
<p style="margin:0;padding:0 0 16px;font-family:${T.font};font-size:11px;line-height:13px;font-weight:700;letter-spacing:1.9px;text-transform:uppercase;color:${c.eyebrow};">${escapeHtml(content.eyebrow)}</p>
<h1 class="pi-title" style="margin:0;padding:0 0 32px;font-family:${T.font};font-size:38px;line-height:41px;font-weight:700;letter-spacing:-1.7px;color:${c.heading};">${title}</h1>
<p class="pi-text" style="${text}padding:0 0 20px;font-weight:700;color:${c.heading};">${escapeHtml(copy.hello(greetingNameOf(content.greetingName)))}</p>
${paragraphs.join('\n')}
${detailsHtml}
${cta}
${footnote}
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-top:34px;"><tr><td height="1" bgcolor="${c.divider}" style="height:1px;background:${c.divider};font-size:0;line-height:0;">&nbsp;</td></tr></table>
<p style="margin:0;padding:26px 0 0;font-family:${T.font};font-size:15px;line-height:22px;color:${c.signature};">${escapeHtml(copy.signature[0])}</p>
<p style="margin:0;padding:2px 0 0;font-family:${T.font};font-size:15px;line-height:22px;font-weight:700;color:${c.heading};">${escapeHtml(copy.signature[1])}</p>
</td></tr>
<tr><td bgcolor="${c.contactBackground}" class="pi-pad" style="background:${c.contactBackground};border-radius:0 0 ${T.radius}px ${T.radius}px;padding:24px ${pad}px 25px;">
<p style="margin:0;padding:0 0 9px;font-family:${T.font};font-size:16px;line-height:20px;font-weight:700;color:${c.contactHeading};">${escapeHtml(copy.contactTitle)}</p>
<p style="margin:0;padding:0 0 4px;font-family:${T.font};font-size:14px;line-height:18px;color:${c.contactText};">${escapeHtml(copy.contactText)}</p>
<p style="margin:0;font-family:${T.font};font-size:14px;line-height:18px;"><a href="mailto:${attr(ctx.contactEmail)}" style="color:${c.contactHeading};text-decoration:underline;">${escapeHtml(ctx.contactEmail)}</a></p>
</td></tr>
<tr><td align="center" style="padding:28px ${pad}px 0;">
<p style="margin:0;padding:0 0 4px;font-family:${T.font};font-size:12px;line-height:14px;text-transform:uppercase;color:${c.footer};">${escapeHtml(T.brand.footer)}</p>
<p style="margin:0;font-family:${T.font};font-size:12px;line-height:16px;color:${c.footer};">${escapeHtml(copy.generated)}</p>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>`
}
